export type Profile = { goal_text: string; role: string | null; goal_skills: string[]; known_skills: string[]; weekly_hours: number; horizon_weeks: number; level: number; style: "balanced" | "project first" | "theory first" };
export type Module = { skill: string; name: string; resource: { id: string; title: string; provider: string; url: string; hours: number } | null };
export type PathData = { profile: Profile; path: { total_weeks: number; feasible: boolean; phases: { title: string; modules: Module[]; weeks: [number, number] }[] }; progress: { skills_done: number; skills_total: number; percent: number; hours_done: number; hours_total: number; weeks_left: number | null; current_phase: string | null; next_action: Module | null }; state: { completed: string[]; blocked: string[] } };
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
export const defaultProfile: Profile = { goal_text: "", role: null, goal_skills: [], known_skills: [], weekly_hours: 5, horizon_weeks: 24, level: 2, style: "balanced" };
async function request(endpoint: string, body: object): Promise<PathData> { const response = await fetch(`${API}${endpoint}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.detail ?? "The learning engine is unavailable."); return response.json(); }
export const generatePath = (profile = defaultProfile, completed: string[] = [], blocked: string[] = []) => request("/path", { profile, completed, blocked });
export const completeModule = (profile: Profile, completed: string[], blocked: string[], skill: string) => request("/path/feedback", { profile, completed, blocked, event: "completed", skill });
export type ChatResponse = { reply: string; data?: PathData; profile?: Partial<Profile> };
export async function chat(message: string, profile: Profile | null, completed: string[], blocked: string[]): Promise<ChatResponse> { const response = await fetch(`${API}/chat`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message, profile, completed, blocked }) }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.detail ?? "The AI co-pilot is unavailable."); return response.json(); }
